---
- name: Install dev headers
  become: true
  tags:
    - dev
  block:
    - name: Install dev headers (Ubuntu)
      ansible.builtin.apt:
        name:
          - libssl-dev
          - libxml2-utils
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu"
